FROM node:22

WORKDIR /app

# Dodaj curl, jeśli chcesz tailwinda CLI też tutaj
RUN apt-get update && apt-get install -y curl

# Kopiujemy pliki package.json
COPY app/package*.json ./
RUN npm install

# Tailwind CLI (opcjonalnie)
RUN curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 && \
    chmod +x tailwindcss-linux-x64 && \
    mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss

RUN npm install -D @tailwindcss/postcss autoprefixer

# Pracujemy z lokalnym kodem przez volume
CMD ["npm", "start"]
