services:
  react-dev:
    image: node:22
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true # dla hot-reload na Docker Desktop

#  react-prod:
#    build: .
#    ports:
#      - "8080:80"
#    depends_on:
#      - react-dev
