services:
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_API_TOKEN: ${REACT_APP_API_TOKEN}
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true # dla hot-reload na Docker Desktop
      - REACT_APP_API_TOKEN=${REACT_APP_API_TOKEN}
    env_file:
      - .env.dev

  react-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_TOKEN: ${REACT_APP_API_TOKEN}
    ports:
      - "8080:80"
#    depends_on:
#      - react-dev
